/* eslint-disable react-hooks/exhaustive-deps */
"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Files, Eye, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Pagination } from "@/components/common/Pagination";
import { rowPerPage } from "@/lib/constant";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { getReportByUsers } from "@/app/api/apartment";
import { useAuth } from "@/components/authentication/AuthProvider";
import { useRouter } from "next/navigation";

const HistoryList = () => {
  const { toast } = useToast();
  const router = useRouter();
  const [currentPage, setCurrentPage] = useState(1);
  const [reports, setReports] = useState<any[]>([]);
  const [totalReports, setTotalReports] = useState(0);
  const [loading, setLoading] = useState(false);
  const { user, isLoading } = useAuth();
  const userId = user?._id;

  useEffect(() => {
    if (!isLoading && userId) {
      fetchReports();
    }
  }, [userId, currentPage, isLoading]);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const skip = (currentPage - 1) * rowPerPage;
      const response = await getReportByUsers(rowPerPage, skip, userId);
      setReports(response.report || []);
      setTotalReports(response.total || 0);
    } catch (err: any) {
      toast({
        title: "Failed to load Report ❌",
        description: err.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const viewPage = (id: string, type: string) => {
    switch (type) {
      case "Apartment":
        router.push(`/apartment-details/${id}`);
        break;

      case "Commercial":
        router.push(`/commercial-details/${id}`);
        break;

      case "Villa":
      case "Independent":
        router.push(`/villa-details/${id}`);
        break;

      case "Land":
        router.push(`/land-details/${id}`);
        break;

      default:
        console.warn("Unknown property type:", type);
    }
  };

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };

  return (
    <div className="w-full">
      <Header />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <div className="pb-8">
          <div className="flex items-center justify-center py-5">
            <div className="py-3">
              <h1 className="text-3xl font-bold text-slate-800">
                My Reports History
              </h1>
              <p className="text-slate-600">
                View all valuation reports generated by you
              </p>
            </div>
          </div>

          {/* Reports Table */}
          <Card>
            <CardHeader>
              <CardTitle className="text-left">Reports</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="rounded-md border">
                {loading ? (
                  <div className="flex items-center justify-center min-h-[200px]">
                    <div className="text-center">
                      <Loader2 className="h-12 w-12 animate-spin text-emerald-600 mx-auto mb-4" />
                    </div>
                  </div>
                ) : reports.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-16 text-slate-500">
                    <Files className="h-10 w-10 mb-2" />
                    <p>No reports found.</p>
                  </div>
                ) : (
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Address</TableHead>
                        <TableHead>Property Type</TableHead>
                        <TableHead>Carpet Area</TableHead>
                        <TableHead>Super BuiltUp Area</TableHead>
                        <TableHead>Price</TableHead>
                        <TableHead>Date</TableHead>
                        <TableHead>Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {reports.map((rep) => (
                        <TableRow key={rep._id}>
                          <TableCell className="text-left">
                            {rep.address}
                          </TableCell>
                          <TableCell className="text-left">
                            {rep.type_of_property}
                          </TableCell>
                          <TableCell>{rep?.carpet_area ?? "-"}</TableCell>
                          <TableCell>
                            {rep.super_built_up_area ?? "-"}
                          </TableCell>
                          <TableCell>{rep.final_valuation ?? "-"}</TableCell>
                          <TableCell>{rep.report_date ?? "-"}</TableCell>
                          <TableCell className="text-right">
                            <div className="flex items-center justify-end space-x-2">
                              <Button
                                size="sm"
                                variant="outline"
                                className="h-8 w-8 p-0"
                                onClick={() =>
                                  viewPage(rep?._id, rep?.type_of_property)
                                }
                              >
                                <Eye className="h-3 w-3" />
                              </Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                )}
              </div>
              <Pagination
                currentPage={currentPage}
                totalItems={totalReports}
                itemsPerPage={rowPerPage}
                onPageChange={handlePageChange}
              />
            </CardContent>
          </Card>
        </div>
      </div>
      <Footer />
    </div>
  );
};
export default HistoryList;
